'use strict';

var $ = require('jquery');
var UI = require("./core");
require("./util.hammer");
require("./ui.add2home");
require("./ui.alert");
require("./ui.button");
require("./ui.collapse");
require("./ui.datepicker");
require("./ui.dimmer");
require("./ui.dropdown");
require("./ui.flexslider");
require("./ui.iscroll-lite");
require("./ui.modal");
require("./ui.offcanvas");
require("./ui.pinchzoom");
require("./ui.popover");
require("./ui.progress");
require("./ui.pureview");
require("./ui.scrollspy");
require("./ui.scrollspynav");
require("./ui.selected");
require("./ui.share");
require("./ui.smooth-scroll");
require("./ui.sticky");
require("./ui.tabs");
require("./ui.ucheck");
require("./ui.validator");
require("./util.cookie");
require("./util.fullscreen");
require("./util.geolocation");
require("./util.qrcode");
require("./util.store");
require("../widget/accordion/src/accordion.js");
require("../widget/divider/src/divider.js");
require("../widget/duoshuo/src/duoshuo.js");
require("../widget/figure/src/figure.js");
require("../widget/footer/src/footer.js");
require("../widget/gallery/src/gallery.js");
require("../widget/gotop/src/gotop.js");
require("../widget/header/src/header.js");
require("../widget/intro/src/intro.js");
require("../widget/list_news/src/list_news.js");
require("../widget/map/src/map.js");
require("../widget/mechat/src/mechat.js");
require("../widget/menu/src/menu.js");
require("../widget/navbar/src/navbar.js");
require("../widget/pagination/src/pagination.js");
require("../widget/paragraph/src/paragraph.js");
require("../widget/slider/src/slider.js");
require("../widget/tabs/src/tabs.js");
require("../widget/titlebar/src/titlebar.js");
require("../widget/wechatpay/src/wechatpay.js");

module.exports = $.AMUI = UI;
