language: node_js
node_js:
  - '0.10'
before_install:
  - currentfolder=${PWD##*/}
  - if [ "$currentfolder" != 'generator-amuiwidget' ]; then cd .. && eval "mv $currentfolder generator-amuiwidget" && cd generator-amuiwidget; fi

